let button = document.getElementsByClassName("button")[0];

button.addEventListener("click", function(){
    let birthInfo = document.getElementsByClassName("dateInput")[0].value;
    let birthInfoMonth = birthInfo.split("-")[1];
    let birthInfoDay = birthInfo.split("-")[2];
    console.log(birthInfoMonth, birthInfoDay);


    if((birthInfoMonth == 1 && birthInfoDay <= 20) || (birthInfoMonth == 12 && birthInfoDay >=22)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Capricorn";
        document.getElementsByClassName("horoscope")[0].innerHTML="Looking good and feeling great should be your top priorities now. Start by doing one of your favorite activities to set a positive tone for the day. Then, spend a little extra time with your appearance, choosing patterns and colors that enhance your best physical features. As you start turning heads, your confidence will soar and there will be no stopping your ambition. Instead of feeling like you have to settle, you'll be in the position to choose which job offers, romantic experiences, and social engagements will bring you the best results.";
    } else if ((birthInfoMonth == 1 && birthInfoDay >= 21) || (birthInfoMonth == 2 && birthInfoDay <= 18)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Aquarius";
        document.getElementsByClassName("horoscope")[0].innerHTML="Your willingness to serve others is greatly appreciated. Take this opportunity to do something nice for someone who works on the front line of a stressful field, like a teacher, nurse, or grocery store clerk. If you’re not sure how to demonstrate your appreciation, ask your best friend or romantic partner for advice. They’ll have a great suggestion that makes a big impact. The faster you perform this good deed today, the happier you will be. Prolonging this task will just make you second-guess yourself; your heart is in the right place.";
    } else if((birthInfoMonth == 2 && birthInfoDay >= 19) || (birthInfoMonth == 3 && birthInfoDay <= 20)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Pisces";
        document.getElementsByClassName("horoscope")[0].innerHTML="If you long to connect with your tribe, organize a big video chat today where everyone can see each other's faces. It will be so much fun catching up on your lives and comparing notes about current events. One of your most optimistic friends could make you realize how fortunate you are now, despite the world's struggles. After this inspiring conversation, you could decide to return to an abandoned art project. The creative blocks that once plagued you seem to have vanished into thin air. There’s a good chance you’ll work all night, fueled by excitement and adrenaline.";
    } else if((birthInfoMonth == 3 && birthInfoDay >= 21) || (birthInfoMonth == 4 && birthInfoDay <= 20)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Aries";
        document.getElementsByClassName("horoscope")[0].innerHTML="Although you have a reputation for being a tough customer, there’s a very tender side to your personality that you often keep hidden from view. Be willing to let down your guard and put your loving heart on display today. Doing something kind and generous for a relative or close friend will put you in line for an extra dose of love, luck, or prosperity. The universe has a way of rewarding those who embody its boundless abundance. As a result, taking a small emotional or financial risk could pay off handsomely this evening.";
    } else if((birthInfoMonth == 4 && birthInfoDay >= 21) || (birthInfoMonth == 5 && birthInfoDay <= 20)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Taurus";
        document.getElementsByClassName("horoscope")[0].innerHTML="An upbeat mood draws people to you like a magnet today. While it’s still important to keep distance, that shouldn’t stop you from having a pleasant conversation with someone while running an errand or walking your dog. Widening your social network may even help improve your financial prospects. It’s possible a neighbor will offer you a great job now that Venus, your ruling planet, is entering your 3rd House of Nearby Places. Following up on this lead is worthwhile; this position will not only pay well, but it could allow you to exercise your creative talent.";
    } else if((birthInfoMonth == 5 && birthInfoDay >= 21) || (birthInfoMonth == 6 && birthInfoDay <= 20)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Gemini";
        document.getElementsByClassName("horoscope")[0].innerHTML="There’s nothing wrong with desiring and appreciating luxury; we are physical beings, so it makes sense that we enjoy things that pleasantly engage our five senses. Take this opportunity to treat yourself to a delicious meal, a bewitching fragrance, or brand-new bed sheets. Any item that makes your body sing with pleasure is worth the money; not only will you enjoy the experience, but you'll be more present in the moment. Friends will admire your dedication to happiness and comfort and you may even inspire them to take better care of themselves. You set a wonderful example of self-love.";
    } else if((birthInfoMonth == 6 && birthInfoDay >= 22) || (birthInfoMonth == 7 && birthInfoDay <= 22)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Cancer";
        document.getElementsByClassName("horoscope")[0].innerHTML="Demonstrating your affection comes naturally to you. Although you’re extremely private, that doesn’t keep you from showering your favorite people with affection. Your nearest and dearest are so grateful for these tender tributes; everyone is in desperate need of tender loving care these days. Expressing appreciation for customers, patients, patients, or clients is especially important. While others are struggling in the professional realm, your career prospects could improve because of your excellent interpersonal skills. If you have a brilliant idea for a new product or service, now is the time to launch it.";
    } else if((birthInfoMonth == 7 && birthInfoDay >= 23) || (birthInfoMonth == 8 && birthInfoDay <= 23)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Leo";
        document.getElementsByClassName("horoscope")[0].innerHTML="Stepping out of the public eye seems counterintuitive for a superstar like you, but try it anyway. It can be such a relief to stop worrying about what others think and turn your attention inward. You’re a very deep person who harbors strong passions. Today, devote your energy to art, music, film, and whatever other creative forms of expression make your spirits soar. After you’ve engaged this colorful side of yourself, you’ll re-emerge feeling feisty and flirtatious. People will be even more enamored of you, realizing how dull life is when you’re not around.";
    } else if((birthInfoMonth == 8 && birthInfoDay >= 24) || (birthInfoMonth == 9 && birthInfoDay <= 23)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Virgo";
        document.getElementsByClassName("horoscope")[0].innerHTML="When it comes to satisfying yourself, you tend to be cool, calm, and detached. Rather than worrying what everyone else will think of your behavior, you’ll gladly take time off work to have some fun today. It may be wise to refrain from posting on social media while you’re taking this break, as jealous colleagues could bring this matter to your boss’ attention. Fortunately, you don’t need to put your life on display to feel validated. Use this respite to commune with nature or catch up on your reading. You'll return to your daily life more energetic and productive than ever.";
    } else if((birthInfoMonth == 9 && birthInfoDay >= 24) || (birthInfoMonth == 10 && birthInfoDay <= 23)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Libra";
        document.getElementsByClassName("horoscope")[0].innerHTML="All eyes are on you as your ruling planet, Venus, enters your 10th House of Publicity and Profession today, further emphasizing your natural charm and artistic talent. Landing a high-profile job in the creative arena is a distinct possibility. If you’re happy with your current employment situation, you might decide to assume a public role that will allow you to make life much more pleasant for others. You may draw on your extensive social network to raise funds for a beautification project. Providing people with a lovely place to rest, relax, and reflect will be a tremendous source of pride.";
    } else if((birthInfoMonth == 10 && birthInfoDay >= 24) || (birthInfoMonth == 11 && birthInfoDay <= 22)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Scorpio";
        document.getElementsByClassName("horoscope")[0].innerHTML="A fascination with a foreign culture could prompt you to learn a new language. Even if you can’t go into a classroom today, you can take an online course or learn through a book or app. You might even prefer studying from home, since it allows you to practice without being observed by fellow students. Still, there’s a good possibility that you’ll pick up the basics quickly and easily. Soon, you may be proficient enough to travel to your dream destination and converse with locals. This could even lead to an opportunity to work overseas. Expanding your skills opens new doors.";
    } else if((birthInfoMonth == 11 && birthInfoDay >= 23) || (birthInfoMonth == 12 && birthInfoDay <= 21)) {
        document.getElementsByClassName("result")[0].innerHTML="You're a Sagittarius";
        document.getElementsByClassName("horoscope")[0].innerHTML="Your magnetism is at an all-time high, so use it to get favors, win hearts, and change minds. If you need a bank loan or scholarship, apply for one today. It doesn’t matter if you’ve been turned down for such assistance in the past; your luck may be improving. Your tenacity could also result in an extraordinary travel opportunity. Getting a chance to travel for business, pleasure, or education could be a pivotal moment in your life. You’ve got a naturally expansive personality, so you should take advantage of any opportunity to broaden your horizons.";
    }else{
        document.getElementsByClassName("result")[0].innerHTML="Please re-enter your date";
    }
});
